fail

diff --git a/.github/workflows/test_workflow.yml b/.github/workflows/test_workflow.yml
--- a/.github/workflows/test_workflow.yml
+++ b/.github/workflows/test_workflow.yml
@@ -19,5 +19,5 @@ jobs:
       - name: Check for failure condition
         run: |
           echo "Current SHA: ${{ github.sha }}"
-          echo "Failing"
-          exit 0
+          echo "Failing..."
+          exit 1
