fail second job

diff --git a/.github/workflows/test_workflow.yml b/.github/workflows/test_workflow.yml
--- a/.github/workflows/test_workflow.yml
+++ b/.github/workflows/test_workflow.yml
@@ -35,8 +35,8 @@ jobs:
             echo "Simulating failure for this commit."
             exit 1
           fi
-          echo "Fail anyways!"
-          exit 1
+          echo "Success!"
+          exit 0
   build:
     runs-on: ubuntu-latest
     steps:
@@ -44,5 +44,5 @@ jobs:
         run: |
           echo "Current SHA: ${{ github.sha }}"
           echo "Build Job"
-          echo "Success!"
-          exit 0
+          echo "Fail!"
+          exit 1
